# Generated by Django 2.1.5 on 2021-11-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barryapp', '0003_auto_20211106_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='title',
            field=models.TextField(max_length=200),
        ),
    ]
