# Generated by Django 2.1.5 on 2021-11-08 05:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barryapp', '0007_header_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='author',
            field=models.ForeignKey(default=None, on_delete=models.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
