# Generated by Django 2.1.5 on 2021-11-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barryapp', '0008_auto_20211108_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='author',
        ),
        migrations.AddField(
            model_name='header',
            name='tag',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='header',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
