# Generated by Django 2.1.5 on 2021-11-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barryapp', '0010_auto_20211108_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Images3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Images4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Text3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('desc', models.CharField(max_length=2000, null=True)),
            ],
        ),
    ]
