# Generated by Django 2.1.5 on 2021-11-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barryapp', '0012_slide1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('desc', models.CharField(max_length=2000, null=True)),
                ('images', models.ImageField(upload_to='images')),
                ('tag', models.TextField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Slide3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('desc', models.CharField(max_length=2000, null=True)),
                ('images', models.ImageField(upload_to='images')),
                ('tag', models.TextField(blank=True, default='', max_length=50)),
            ],
        ),
    ]
