# Generated by Django 2.1.5 on 2021-11-09 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barryapp', '0016_text4'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slide2',
        ),
    ]
