# Generated by Django 2.1.5 on 2021-11-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barryapp', '0021_auto_20211110_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beginner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=200)),
            ],
        ),
    ]
