# Generated by Django 2.1.5 on 2021-11-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barryapp', '0023_professional_standard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Textbooknow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('desc', models.CharField(max_length=2000)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
