# Generated by Django 2.1.5 on 2021-11-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barryapp', '0024_textbooknow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.TextField(max_length=2000)),
                ('Pincode', models.CharField(max_length=20)),
                ('card_type', models.TextField()),
                ('card_number', models.TextField(max_length=50)),
                ('expiry_date', models.TextField()),
                ('Gender', models.CharField(max_length=10)),
                ('cvv', models.TextField(max_length=3)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='beginner',
            name='price',
            field=models.IntegerField(),
        ),
    ]
