# Generated by Django 2.1.5 on 2021-11-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barryapp', '0025_auto_20211121_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cvv',
            field=models.TextField(),
        ),
    ]
