# Generated by Django 2.1.5 on 2021-11-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barryapp', '0027_auto_20211121_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
