# Generated by Django 2.1.5 on 2021-11-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barryapp', '0031_auto_20211122_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(default=False),
        ),
    ]
