# Generated by Django 2.1.5 on 2021-11-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barryapp', '0032_payment_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beginnerpay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('amount', models.IntegerField(default=False)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=2000)),
                ('payment_id', models.CharField(max_length=100, null=True)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
