# Generated by Django 3.2.9 on 2021-11-25 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barryapp', '0034_auto_20211124_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beginnerpay',
            name='amount',
        ),
    ]
