# Generated by Django 3.2.9 on 2021-11-25 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barryapp', '0035_remove_beginnerpay_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Beginnerpay',
        ),
    ]
