# Generated by Django 3.2.9 on 2021-12-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barryapp', '0038_auto_20211204_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applynow',
            name='name',
            field=models.CharField(max_length=122, null=True),
        ),
    ]
