# Generated by Django 3.2.9 on 2021-12-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barryapp', '0039_alter_applynow_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applynow',
            name='email',
            field=models.EmailField(max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='applynow',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='applynow',
            name='portfoliolink',
            field=models.CharField(max_length=122, null=True),
        ),
    ]
